const data = {
  platformLevel: {
    users: [
      {
        fname: "Platform",
        lname: "Admin",
        envVar:
          process.env.SOURCE === "outlook" ? "PLATFORM_ADMIN" : "PLATFORM",
      },
      {
        fname: "Org",
        lname: "Admin 1",
        envVar: process.env.SOURCE === "outlook" ? "ORG_ADMIN1" : "ORGADM1",
      },
      {
        fname: "Org",
        lname: "Admin 2",
        envVar: process.env.SOURCE === "outlook" ? "ORG_ADMIN2" : "ORGADM2",
      },
      {
        fname: "Org",
        lname: "User 1",
        envVar: process.env.SOURCE === "outlook" ? "ORG_USER1" : "ORGUSR1",
      },
      {
        fname: "Org",
        lname: "User 2",
        envVar: process.env.SOURCE === "outlook" ? "ORG_USER2" : "ORGUSR2",
      },
    ],
    organizations: [
      {
        name: "Org 1",
        address: "Marseille",
        adminName: "Org Admin 1",
        adminEmail:
          process.env.SOURCE === "outlook"
            ? process.env.ORG_ADMIN1
            : process.env.ORGADM1,
        ecoOperatorNo: "123",
        vatNo: "456",
        country: "France",
        website: "org1.com",
        type: "legal",
      },
      {
        name: "Org 2",
        address: "Rotterdam",
        adminName: "Org Admin 2",
        adminEmail:
          process.env.SOURCE === "outlook"
            ? process.env.ORG_ADMIN2
            : process.env.ORGADM2,
        ecoOperatorNo: "456",
        vatNo: "123",
        country: "Netherlands",
        website: "org2.com",
        type: "legal",
      },
    ],
    scopes: [
      {
        scopeName: "Facility Scope",
        isccEuCode: "101",
        isccEuLabel: "Iscc_EU",
        redCertEuCode: "102",
        redCertEuLabel: "Redcert_EU",
        twoBsVsCode: "103",
        twoBsVsLabel: "2Bsvs_EU",
      },
      {
        scopeName: "Certificate Scope",
        isccEuCode: "104",
        isccEuLabel: "Iscc_EU",
        redCertEuCode: "105",
        redCertEuLabel: "Redcert_EU",
        twoBsVsCode: "106",
        twoBsVsLabel: "2Bsvs_EU",
      },
    ],
    products: [
      {
        name: "Rapeseed",
        description: "Rapeseed",
        category: "Agri Raw Material",
        measurementType: "Weight",
        lowerHeatingValue: 10,
      },
      {
        name: "Rapeseed Oil",
        description: "Rapeseed Oil",
        category: "Intermediate Product",
        measurementType: "Weight",
        lowerHeatingValue: 20,
      },
      {
        name: "Rapeseed Meal",
        description: "Rapeseed Meal",
        category: "Intermediate Product",
        measurementType: "Weight",
        lowerHeatingValue: 30,
      },
      {
        name: "HVO",
        description: "HVO",
        category: "Final Fuel",
        measurementType: "Weight",
        lowerHeatingValue: 40,
      },
      {
        name: "Naphta",
        description: "Naphta",
        category: "Final Fuel",
        measurementType: "Weight",
        lowerHeatingValue: 50,
      },
      {
        name: "Propane",
        description: "Propane",
        category: "Final Fuel",
        measurementType: "Weight",
        lowerHeatingValue: 60,
      },
    ],
    documentTypes: [
      {
        docType: "PoS",
        description: "Proof of Sustainability",
        isOcr: true,
        configurationId: "6667cde8668f2e4045522cd5",
      },
      {
        docType: "Sustainability Declaration",
        description: "Sustainability Declaration",
        isOcr: true,
        configurationId: "661cb43af502976f55ae9d4f",
      },
    ],
    ocrIds: [
      {
        docName: "SD",
        id: "661cb43af502976f55ae9d4f",
      },
      {
        docName: "PoS",
        id: "6667cde8668f2e4045522cd5",
      },
    ],
    attributes: [
      {
        name: "Country of Biofuel Production",
        description: "Country of Biofuel Production",
        attributeType: "countrySelect",
        attributeLevel: "Twin",
      },
      {
        name: "Energy Content",
        description: "Energy Content",
        attributeType: "numericInput",
        attributeLevel: "Twin",
      },
      {
        name: "Start Date of Biofuel Production",
        description: "Start Date of Biofuel Production",
        attributeType: "singleDatePicker",
        attributeLevel: "Twin",
      },
      {
        name: "Start Date of Production at the Facility",
        description: "Start Date of Production at the Facility",
        attributeType: "singleDatePicker",
        attributeLevel: "Twin",
      },
    ],
    defaultAttribute: {
      onChainFunctionName: "updateIpfsHash",
      privilageName: "ipfs_priv",
      privilageIndex: 5,
      ipfs: true,
    },
    identifiers: [
      {
        name: "Country of Biofuel Production",
        description: "Country of Biofuel Production",
        attributes: ["Country of Biofuel Production"],
        identifierType: false,
        identifierWidth: "Half",
      },
      {
        name: "Energy Content",
        description: "Energy Content",
        attributes: ["Energy Content"],
        identifierType: false,
        identifierWidth: "Half",
      },
      {
        name: "Start Date of Biofuel Production",
        description: "Start Date of Biofuel Production",
        attributes: ["Start Date of Biofuel Production"],
        identifierType: false,
        identifierWidth: "Half",
      },
      {
        name: "Start Date of Production at the Facility",
        description: "Start Date of Production at the Facility",
        attributes: ["Start Date of Production at the Facility"],
        identifierType: false,
        identifierWidth: "Half",
      },
    ],
    events: {
      createPassport: {
        name: "Create Passport",
        description: "Create Passport Event",
        type: "Create Passport",
        icon: "Production",
        actionName: "Create Passport",
        identifiers: [
          "Unique number of Sustainability Declaration",
          "Date of Issuance of Sustainability Declaration",
          "Supplier",
          "Address of dispatch/shipping point of the sustainable material",
          "Address of receipt/receiving point of the sustainable material",
          "Date of dispatch of the sustainable material",
          "Batch has arrived at facility",
          "Please specify the expected date of arrival",
          "Type of Product",
          "Type of raw material",
          "Facility",
          "Additional information",
          "Country of origin",
          "Quantity",
          "Energy Content",
          "EU RED Compliant material",
          "Scheme Compliance",
          "Chain of custody",
          "Country of Biofuel Production",
          "Start Date of Biofuel Production",
          "Start Date of Production at the Facility",
          "The raw material complies with the relevant sustainability criteria according to Art.29(2) - (7) RED II3",
          "The agricultural biomass was cultivated as intermediate crop",
          "The agricultural biomass additionally fulfills the measures for low ILUC risk feedstocks",
          "The raw material meets the definition of waste or residue according to the RED II4",
          "Total default value according to RED II applied",
          "Emissions",
          "Transport Distance",
          "Disaggregated default value for oil extraction",
          "Disaggregated default value for soil N20 emissions",
          "ESCA: Bonuse of 45g CO2eq/MJ manure in the case animal manure is used as a substrate for the production of biogas and biomethane",
          "EL: Bonus of 29g CO2eq/MJ biofuel/bioliquid/biomass fuel if biomass is obtained from restored degraded land",
        ],
        mandatoryIdentifiers: [
          "Unique number of Sustainability Declaration",
          "Date of Issuance of Sustainability Declaration",
          "Supplier",
          "Type of Product",
          "Type of raw material",
          "Facility",
          "Country of origin",
          "Quantity",
          "Scheme Compliance",
          "Chain of custody",
        ],
        journeyText: "Passport Created For :df.Product Type: ",
      },
      oilExtraction: {
        name: "Oil Extraction",
        description: "Oil Extraction Event",
        type: "Generic Event",
        icon: "Conversion",
        actionName: "Oil Extraction",
        filterType: "Type of Product",
        filterValue: "Rapeseed",
        identifiers: ["Processing Date", "Processing Country"],
        mandatoryIdentifiers: ["Processing Date", "Processing Country"],
        journeyText: "Oil Extraction",
        passportOutputs: {
          output1: {
            name: "Rapeseed Oil",
            category: "Intermediate Product",
            conversionFactor: "45",
            feedStockFactor: "222",
            allocationFactor: "70",
          },
          output2: {
            name: "Rapeseed Meal",
            category: "Intermediate Product",
            conversionFactor: "55",
            feedStockFactor: "0",
            allocationFactor: "30",
          },
        },
        ep: "121",
      },
      hvoProduction: {
        name: "HVO Production",
        description: "HVO Production Event",
        type: "Generic Event",
        icon: "Production",
        actionName: "HVO Production",
        filterType: "Type of Product",
        filterValue: "Rapeseed Oil",
        identifiers: ["Production Date", "Production Country"],
        mandatoryIdentifiers: ["Production Date", "Production Country"],
        journeyText: "HVO Production",
        passportOutputs: {
          output1: {
            name: "HVO",
            category: "Final Fuel",
            conversionFactor: "87",
            feedStockFactor: "110",
            allocationFactor: "92",
            eecDDV: "33.40",
            epDDV: "15",
            etdDDV: "1.7",
            tdv: "50.1",
          },
          output2: {
            name: "Naphta",
            category: "Final Fuel",
            conversionFactor: "4",
            feedStockFactor: "110",
            allocationFactor: "4",
          },
          output3: {
            name: "Propane",
            category: "Final Fuel",
            conversionFactor: "3",
            feedStockFactor: "110",
            allocationFactor: "3",
          },
        },
        ep: "450",
      },
      initiateSale: {
        name: "Initiate Sale",
        description: "Initiate Sale Event",
        type: "Sale Initiation",
        icon: "Ownership",
        actionName: "Initiate Sale",
        journeyText: "Sale Initiation",
      },
      productLoss: {
        name: "Product Loss",
        description: "Product Loss Event",
        type: "Generic Event",
        icon: "Generic Event",
        actionName: "Product Loss",
        identifiers: [
          "Initial Quantity",
          "Lost Quantity",
          "Remaining Quantity",
          "Share Of Product Lost",
          "Event Date",
          "Additional information",
        ],
        mandatoryIdentifiers: [
          "Initial Quantity",
          "Lost Quantity",
          "Remaining Quantity",
        ],
        formula1: ":twin.quantity:-:df.Lost Quantity:",
        formula2: "(:df.Lost Quantity: / :twin.quantity: ) * 100",
        journeyText: "Product Loss",
      },
      splitPassport: {
        name: "Split Passport",
        description: "Split Passport Event",
        type: "Split Passport",
        icon: "Conversion",
        actionName: "Split Passport",
        identifiers: [
          "Initial Quantity",
          "Split Quantity",
          "Remaining Quantity",
        ],
        mandatoryIdentifiers: [
          "Initial Quantity",
          "Split Quantity",
          "Remaining Quantity",
        ],
        formula: ":twin.quantity: - :df.New Quantity:",
        relationship: {
          left: "Split Quantity",
          comparator: "Lesser than",
          right: "Initial Quantity",
        },
        journeyText: "Split Passport",
      },
      blend: {
        name: "Blend",
        description: "Blend Event",
        type: "Generic Event",
        icon: "Conversion",
        actionName: "Blend",
        filterType: "Type of raw material",
        filterValue: "Final Fuel",
        identifiers: [
          "Initial Quantity",
          "Blend Type",
          "Fossil Fuel",
          "Fossil Fuel Quantity",
          "Event Date",
          "Share of Biofuel",
        ],
        mandatoryIdentifiers: [
          "Blend Type",
          "Fossil Fuel",
          "Fossil Fuel Quantity",
          "Share of Biofuel",
        ],
        formula:
          "(:twin.quantity: / (:df.Blend Quantity:  + :twin.quantity: )) * 100",
        journeyText: "Blended :df.Blend Type: of :df.Share of Biofuel: %",
      },
    },
  },
  organizationLevel: {
    organization1: {
      users: [
        {
          userEmail:
            process.env.SOURCE === "outlook"
              ? process.env.ORG_USER1
              : process.env.ORGUSR1,
        },
      ],
      facilities: [
        {
          name: "Facility 1",
          address: "Porte 3C Port de Marseille Fos",
          city: "Marseille",
          country: "France",
          postcode: "13015",
          latitude: 0,
          longitude: 0,
          massBalanceStartDate: "2024-07-24",
          massBalanceDuration: "3",
          productionStartDate: "2024-07-25",
          certificationScopes: ["Facility Scope"],
        },
      ],
      certificates: [
        {
          scheme: "ISCC",
          body: "SGS",
          number: "123",
          bodyNumber: "456",
          dateOfIssue: "2024-07-24",
          placeOfIssue: "Paris",
          dateOfOriginalIssue: "2024-07-23",
          startDate: "2024-07-22",
          endDate: "2024-07-21",
          status: "Valid",
          certificationScope: ["Certificate Scope"],
          facility: ["Facility 1"],
          documentType: "Certificate",
        },
      ],
      attributes: [
        {
          name: "Country of Biofuel Production",
          description: "Country of Biofuel Production",
          attributeType: "countrySelect",
          attributeLevel: "Twin",
        },
      ],
      identifiers: [
        {
          name: "Country of Biofuel Production",
          description: "Country of Biofuel Production",
          attributes: ["Country of Biofuel Production"],
          identifierType: false,
          identifierWidth: "Half",
        },
      ],
      events: {
        ucomeProduction: {
          name: "UCOME Production",
          description: "UCOME Production Event",
          type: "Generic Event",
          icon: "Production",
          actionName: "UCOME Production",
          filterType: "Type of Product",
          filterValue: "UCO",
          identifiers: ["Production Date", "Production Country"],
          mandatoryIdentifiers: ["Production Date", "Production Country"],
          journeyText: "UCOME Production",
          passportOutputs: {
            output1: {
              name: "UCO",
              category: "Final Fuel",
              conversionFactor: "100",
              feedStockFactor: "0",
              allocationFactor: "93.7",
              eecDDV: "0",
              epDDV: "13",
              etdDDV: "1.9",
              tdv: "14.9",
            },
            output2: {
              name: "Glycerol",
              category: "Intermediate Product",
              conversionFactor: "10.6",
              feedStockFactor: "0",
              allocationFactor: "6.3",
            },
          },
          ep: "480",
        },
        rmeProduction: {
          name: "RME Production",
          description: "RME Production Event",
          type: "Generic Event",
          icon: "Production",
          actionName: "RME Production",
          filterType: "Type of Product",
          filterValue: "Rapeseed Oil",
          identifiers: ["Production Date", "Production Country"],
          mandatoryIdentifiers: ["Production Date", "Production Country"],
          journeyText: "RME Production",
          passportOutputs: {
            output1: {
              name: "RME",
              category: "Final Fuel",
              conversionFactor: "99.94",
              feedStockFactor: "100.06",
              allocationFactor: "93.7",
              eecDDV: "32",
              epDDV: "16.3",
              etdDDV: "1.8",
              tdv: "50.1",
            },
            output2: {
              name: "Glycerol",
              category: "Intermediate Product",
              conversionFactor: "0",
              feedStockFactor: "0",
              allocationFactor: "0",
            },
          },
          ep: "450",
        },
      },
      products: [
        {
          name: "UCO",
          description: "Used Cooking Oil",
          category: "Waste/Residue Raw Material",
          measurementType: "Weight",
          lowerHeatingValue: 37,
        },
        {
          name: "UCOME",
          description: "Uco Methyl Ester",
          category: "Final Fuel",
          measurementType: "Weight",
          lowerHeatingValue: 37.2,
        },
        {
          name: "Glycerol",
          description: "Glycerol",
          category: "Intermediate Product",
          measurementType: "Weight",
          lowerHeatingValue: 16,
        },
        {
          name: "RME",
          description: "Rapeseed Methyl Ester",
          category: "Final Fuel",
          measurementType: "Weight",
          lowerHeatingValue: 37.2,
        },
      ],
      clonedEvents: [
        "Create Passport",
        "Oil Extraction",
        "HVO Production",
        "Initiate Sale",
        "Split Passport",
        "Product Loss",
        "Blend",
      ],
      roles: [
        {
          email:
            process.env.SOURCE === "outlook"
              ? process.env.ORG_ADMIN1
              : process.env.ORGADM1,
          roles: [
            "product-release",
            "ucome production",
            "rme production",
            "create passport",
            "oil extraction",
            "hvo production",
            "initiate sale",
            "split passport",
            "product loss",
            "blend",
          ],
        },
        {
          email:
            process.env.SOURCE === "outlook"
              ? process.env.ORG_USER1
              : process.env.ORGUSR1,
          roles: [
            "create passport",
            "oil extraction",
            "hvo production",
            "split passport",
            "product loss",
            "blend",
          ],
        },
      ],
      preferredPartners: [
        {
          name: "Supplier 1",
          address: "Supplier Address",
          ecoOperatorNo: "123",
          vatNo: "456",
          country: "France",
          website: "Supplier1.com",
          type: "Legal",
          facilityName: "Supplier Facility 1",
          facilityAddress: "Supplier Address",
          facilityCity: "Supplier City",
          facilityCountry: "France",
          postCode: "654123",
          latitude: "0",
          longitude: "0",
          massBalanceStartDate: "2024-01-01",
          massBalanceDuration: "12",
          productionStartDate: "2024-01-01",
          role: "Supplier",
        },
        {
          name: "Buyer 1",
          address: "Buyer Address",
          ecoOperatorNo: "789",
          vatNo: "012",
          country: "France",
          website: "Buyer1.com",
          type: "Legal",
          facilityName: "Buyer Facility 1",
          facilityAddress: "Buyer Address",
          facilityCity: "Buyer City",
          facilityCountry: "France",
          postCode: "654123",
          latitude: "0",
          longitude: "0",
          massBalanceStartDate: "2024-01-01",
          massBalanceDuration: "12",
          productionStartDate: "2024-01-01",
          role: "Buyer",
        },
      ],
      docRules: [
        {
          name: "Test",
          description: "Test Rules",
          rules: [
            {
              name: "Rule 1",
              docType: ["Sustainability Declaration", "PoS"],
              rule: ["Additional info", "Is", "Mandatory"],
              customErrorMessage: "Additional info is mandatory",
            },
            {
              name: "Rule 2",
              docType: ["Sustainability Declaration"],
              rule: [
                "Dispatch address",
                "Is",
                "Mandatory",
                "If",
                "Check dispatch address",
                "Is",
                "True",
              ],
              customErrorMessage:
                "Dispatch address is mandatory if check dispatch address is true",
            },
          ],
        },
      ],
    },
    organization2: {
      users: [
        {
          userEmail:
            process.env.SOURCE === "outlook"
              ? process.env.ORG_USER2
              : process.env.ORGUSR2,
        },
      ],
      facilities: [
        {
          name: "Facility 2",
          address: "LK Europoort",
          city: "Rotterdam",
          country: "Netherlands",
          postcode: "3198",
          latitude: 100,
          longitude: 100,
          massBalanceStartDate: "2024-07-24",
          massBalanceDuration: "12",
          productionStartDate: "2024-07-25",
          certificationScopes: ["Facility Scope"],
        },
      ],
      certificates: [
        {
          scheme: "ISCC",
          body: "Control Union",
          number: "456",
          bodyNumber: "789",
          dateOfIssue: "2024-07-24",
          placeOfIssue: "Paris",
          dateOfOriginalIssue: "2024-07-23",
          startDate: "2024-07-22",
          endDate: "2024-07-21",
          status: "Valid",
          certificationScope: ["Certificate Scope"],
          facility: ["Facility 2"],
          documentType: "Certificate",
        },
      ],
      attributes: [
        {
          name: "Country of Biofuel Production",
          description: "Country of Biofuel Production",
          attributeType: "countrySelect",
          attributeLevel: "Twin",
        },
      ],
      identifiers: [
        {
          name: "Country of Biofuel Production",
          description: "Country of Biofuel Production",
          attributes: ["Country of Biofuel Production"],
          identifierType: false,
          identifierWidth: "Half",
        },
      ],
      products: [
        {
          name: "UCO",
          description: "Used Cooking Oil",
          category: "Waste/Residue Raw Material",
          unit: "Weight",
          value: "37",
        },
      ],
      clonedEvents: [
        "Create Passport",
        "Oil Extraction",
        "HVO Production",
        "Initiate Sale",
        "Split Passport",
        "Product Loss",
        "Blend",
      ],
      roles: [
        {
          email:
            process.env.SOURCE === "outlook"
              ? process.env.ORG_ADMIN2
              : process.env.ORGADM2,
          roles: [
            "product-release",
            "create passport",
            "oil extraction",
            "hvo production",
            "initiate sale",
            "split passport",
            "product loss",
            "blend",
          ],
        },
        {
          email:
            process.env.SOURCE === "outlook"
              ? process.env.ORG_USER2
              : process.env.ORGUSR2,
          roles: [
            "create passport",
            "oil extraction",
            "hvo production",
            "split passport",
            "product loss",
            "blend",
          ],
        },
      ],
      preferredPartners: [
        {
          name: "Supplier 2",
          address: "Supplier Address",
          ecoOperatorNo: "345",
          vatNo: "678",
          country: "Netherlands",
          website: "Supplier2.com",
          type: "Legal",
          facilityName: "Supplier Facility 2",
          facilityAddress: "Supplier Address",
          facilityCity: "Supplier City",
          facilityCountry: "Netherlands",
          postCode: "654123",
          latitude: "0",
          longitude: "0",
          massBalanceStartDate: "2024-01-01",
          massBalanceDuration: "12",
          productionStartDate: "2024-01-01",
          role: "Supplier",
        },
        {
          name: "Buyer 2",
          address: "Buyer Address",
          ecoOperatorNo: "901",
          vatNo: "234",
          country: "Netherlands",
          website: "Buyer2.com",
          type: "Legal",
          facilityName: "Buyer Facility 2",
          facilityAddress: "Buyer Address",
          facilityCity: "Buyer City",
          facilityCountry: "Netherlands",
          postCode: "654123",
          latitude: "0",
          longitude: "0",
          massBalanceStartDate: "2024-01-01",
          massBalanceDuration: "12",
          productionStartDate: "2024-01-01",
          role: "Buyer",
        },
      ],
      docRules: [
        {
          name: "Test",
          description: "Test Rules",
          rules: [
            {
              name: "Rule 1",
              docType: ["Sustainability Declaration", "PoS"],
              rule: ["Additional info", "Is", "Mandatory"],
              customErrorMessage: "Additional info is mandatory",
            },
            {
              name: "Rule 2",
              docType: ["Sustainability Declaration"],
              rule: [
                "Dispatch address",
                "Is",
                "Mandatory",
                "If",
                "Check dispatch address",
                "Is",
                "True",
              ],
              customErrorMessage:
                "Dispatch address is mandatory if check dispatch address is true",
            },
          ],
        },
      ],
    },
  },
  partners: [
    {
      mailId: process.env.SOURCE === "outlook" ? "ORG_ADMIN1" : "ORGADM1",
      selfOrg: "org 1",
      partnerOrg: "org 2",
      option: "Buyer",
    },
    {
      mailId: process.env.SOURCE === "outlook" ? "ORG_ADMIN2" : "ORGADM2",
      selfOrg: "org 2",
      partnerOrg: "org 1",
      option: "Buyer",
    },
  ],
  smokeData: {
    certificationScope: {
      initial: {
        name: "Test Scope Name",
        isccCode: "ISCC123",
        isccLabel: "ISCC Label",
        redCertCode: "RED123",
        redCertLabel: "RED Label",
        bsvsCode: "BSVS123",
        bsvsLabel: "BSVS Label",
      },
      updated: {
        name: "Updated Scope Name",
        isccCode: "ISCC456",
        isccLabel: "Updated ISCC Label",
        redCertCode: "RED456",
        redCertLabel: "Updated RED Label",
        bsvsCode: "BSVS456",
        bsvsLabel: "Updated BSVS Label",
      },
    },
    product: {
      initial: {
        name: "Test Product",
        desc: "Test Product Description",
        category: "Agri Raw Material",
        measurement: "Weight",
        heatingValue: 123,
      },
      updated: {
        name: "Updated Product",
        desc: "Updated Product Description",
        category: "Intermediate Product",
        measurement: "Volume",
        heatingValue: 456,
      },
    },
    documentType: {
      initial: {
        name: "Test Doc Type",
        description: "Test Document Type Description",
        isOCR: true,
        ocrID: "OCR123",
      },
      updated: {
        name: "Updated Doc Type",
        description: "Updated Document Type Description",
        isOCR: false,
        ocrID: "",
      },
    },
    attribute: {
      initial: {
        name: "Test Attribute",
        description: "Test Attribute Description",
        type: "userSelect",
        level: "Twin",
      },
      updated: {
        name: "Updated Attribute",
        description: "Updated Attribute Description",
        type: "productSelect",
        level: "Event",
      },
    },
    identifier: {
      initial: {
        name: "Test Identifier",
        description: "Test Identifier Description",
        attributes: ["EP"],
        isIdentifierTypeSystem: true,
        width: "Full",
      },
      updated: {
        name: "Updated Identifier",
        description: "Updated Identifier Description",
        attributes: ["ETD"],
        isIdentifierTypeSystem: false,
        width: "Half",
      },
    },
    partner: {
      initial: {
        pname: "Initial Partner Name",
        paddress: "123 Initial Street, Initial City",
        ecomNo: "12345",
        vatNo: "VAT12345",
        pcountry: "France",
        website: "initialpartner.com",
        legalType: "LLC",
        fname: "Initial Facility Name",
        faddress: "456 Facility Street, Facility City",
        city: "Facility City",
        fcountry: "France",
        postcode: "12345",
        latitude: "12.3456",
        longitude: "78.9012",
        massBalanaceDate: "2024-01-01",
        months: "3",
        productionDate: "2024-02-01",
        option: "Supplier",
      },
      updated: {
        pname: "Updated Partner Name",
        paddress: "789 Updated Street, Updated City",
        ecomNo: "54321",
        vatNo: "VAT54321",
        pcountry: "Netherlands",
        website: "updatedpartner.com",
        legalType: "Corporation",
        fname: "Updated Facility Name",
        faddress: "101 Updated Facility Street, Updated Facility City",
        city: "Updated Facility City",
        fcountry: "Netherlands",
        postcode: "54321",
        latitude: "23.4567",
        longitude: "89.0123",
        massBalanaceDate: "2024-06-01",
        months: "12",
        productionDate: "2024-07-01",
        option: "Buyer",
      },
    },
    facility: {
      initial: {
        name: "Test Facility",
        address: "123 Initial Street",
        city: "Initial City",
        country: "France",
        postcode: "12345",
        latitude: "37.7749",
        longitude: "-122.4194",
        massBalanaceDate: "2024-01-01",
        months: "3",
        productionDate: "2024-01-15",
        cerScope: ["Certificate Scope"],
      },
      updated: {
        name: "Updated Facility",
        address: "456 Updated Avenue",
        city: "Updated City",
        country: "Netherlands",
        postcode: "54321",
        latitude: "45.4215",
        longitude: "-75.6972",
        massBalanaceDate: "2024-02-01",
        months: "12",
        productionDate: "2024-02-15",
        cerScope: ["Facility Scope"],
      },
    },
    certificate: {
      initial: {
        cerScheme: "ISCC",
        cerBody: "SGS",
        cerNo: "CERT123",
        cerBodyNo: "BODY123",
        dateOfIssue: "2024-07-24",
        placeOfIssue: "Location A",
        dateOfOriginalIssue: "2024-07-23",
        startDate: "2024-07-22",
        endDate: "2024-07-21",
        cerStatus: "Valid",
        cerScope: ["Facility Scope"],
        facility: ["Facility 1"],
        docformCertificate: "Certificate",
      },
      updated: {
        cerScheme: "RedCert",
        cerBody: "Control Union",
        cerNo: "CERT456",
        cerBodyNo: "BODY456",
        dateOfIssue: "2024-08-24",
        placeOfIssue: "Location B",
        dateOfOriginalIssue: "2024-08-23",
        startDate: "2024-08-22",
        endDate: "2024-08-21",
        cerStatus: "Expired",
        cerScope: ["Certificate Scope"],
      },
    },
    event: {
      initial: {
        name: "Initial Name",
        description: "Initial Event Description",
        eventType: "Sale Initiation",
        icon: "Ownership",
        actionName: "Action 1",
        twinJourneyText: "Initial Text",
      },
      updated: {
        name: "Updated Name",
        description: "Updated Event Description",
        actionName: "Action 2",
        twinJourneyText: "Updated Text",
      },
    },
    recordType: {
      initial: {
        name: "Test",
        fieldValues: ["1", "2"],
      },
      updated: {
        name: "Record",
      },
    },
    validationRule: {
      initial: {
        rules: ["Product type must be HVO", "Country of origin is mandatory"],
        multiRules: [
          "Ensure consistency of the supplier address across Test, Proof of Sustainability, and Purchase Order records.",
          "Ensure consistency of the supplier name across Test, Proof of Sustainability, and Purchase Order records.",
        ],
      },
      updated: {
        rule: "Country of origin is optional",
        multiRule:
          "Ensure consistency of the supplier address across Test and Purchase Order records.",
      },
    },
    record: {
      initial: {
        refName: "BL0001",
      },
      updated: {
        refName: "BL0002",
      },
    },
    reference: {
      refName: "Test Reference",
      updatedName: "Test",
      schema: "Test",
      filePath: "files/RefTest.xlsx",
    },
    createRecord: {
      PoS: {
        source: "file",
        docPath: "files/PoS.pdf",
        recordType: "Proof Of Sustainability",
      },
      PoSBioGas: {
        source: "file",
        docPath: "files/PoSBioGas.pdf",
        recordType: "Proof Of Sustainability - Biogas",
      },
      SD: {
        source: "file",
        docPath: "files/SD.pdf",
        recordType: "Sustainability Declaration",
      },
      UDB: {
        source: "UDB",
      },
      ERP: {
        source: "ERP",
      },
      BOL: {
        source: "file",
        docPath: "files/BLX.pdf",
        docPathXls: "files/BLXS.xls",
        recordType: "Bill Of Lading",
      },
    },
    createReference: {
      refName: "Suppliers",
      schema: [
        "Supplier Name",
        "Certificate Number",
        "Certificate Expiry Date",
      ],
      filePath: "files/Suppliers.xlsx",
    },
  },
};

export default data;
